---
# tasks file for dotqmail
- name: generate dotqmail-files
  template:
    src: templates/dotqmail.j2
    dest: "{{ansible_env.HOME}}/.qmail-{{item.key}}"
    mode: 0644
  with_dict: "{{dotqmail_files}}"

- name: Fetch all dotqmail files
  find:
    paths: "{{ansible_env.HOME}}/"
    patterns: ".qmail*"
    hidden: True
  register: old_dotqmail_files

- name: Test
  debug:
    msg: "File: {{item.path|basename|replace(dotqmail_prefix + '-','')}}"
  with_items: "{{old_dotqmail_files.files}}"


